name: base
channels:
  - conda-forge
dependencies:
  - torch
  - python
  - torchvision
  #- torchinfo
  #- cudatoolkit
  - pip
  - pip:
    - numpy
    - matplotlib
    - notebook
    - jupyter
    #- wandb
    #- tqdm
    #- seaborn
    #- scikit-image
    #- nibabel
    #- pillow
    #- datasets
    #- torchmetrics
    #- accelerate