name: l2dVE
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - torch
  - python
  - torchvision
  #- torchinfo
  #- cudatoolkit
  - pip
  - pip:
    - numpy
    - matplotlib
    - notebook
    - jupyter
    - ipykernel # required for jupyter notebook in VS Code
    #- wandb
    #- tqdm
    #- seaborn
    #- scikit-image
    #- nibabel
    #- pillow
    #- datasets
    #- torchmetrics
    #- accelerate
