name: l2dVE
channels:
  - conda-forge
  - pytorch #https://anaconda.org/pytorch/pytorch
dependencies:
  - python
  #- python==3.11.*
  - pytorch
  - torchvision
  #- torchinfo
  #- cudatoolkit
  - pip
  - pip:
    - numpy
    - matplotlib
    - notebook
    - jupyter
    - ipykernel # required for jupyter notebook in VS Code
    #- wandb
    #- tqdm
    #- seaborn
    #- scikit-image
    #- nibabel
    #- pillow
    #- datasets
    #- torchmetrics
    #- accelerate
