name: l2dVE
channels:
  - conda-forge
  - pytorch #https://anaconda.org/pytorch/pytorch
dependencies:
  - python
  - pandas
  #- python==3.11.*
  - pytorch
  - torchvision
  - gymnasium
  - pygame
  - ipympl
  #- torchinfo
  #- cudatoolkit
  - pip
  - pip:
    - numpy
    - matplotlib
    - notebook
    - jupyter
    - ipykernel # required for jupyter notebook in VS Code
    - scikit-learn
    - medmnist
    - seaborn
    #- wandb
    #- tqdm
    #- scikit-image
    #- nibabel
    #- pillow
    #- datasets
    #- torchmetrics
    #- accelerate
